version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
